package cassette

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
)

type PytestGenerationOptions struct {
	CassettePaths []string
	OutputPath    string
}

func GeneratePytestTests(options PytestGenerationOptions) ([]byte, error) {
	if len(options.CassettePaths) == 0 {
		return nil, fmt.Errorf("at least one cassette is required")
	}
	if options.OutputPath == "" {
		return nil, fmt.Errorf("output path is required")
	}

	cassettes := make([]generatedCassette, 0, len(options.CassettePaths))
	for _, cassettePath := range options.CassettePaths {
		if err := validateGenerationCassette(cassettePath); err != nil {
			return nil, err
		}

		testPath, err := relativeTestPath(cassettePath, options.OutputPath)
		if err != nil {
			return nil, err
		}
		cassettes = append(cassettes, generatedCassette{
			Path: testPath,
			ID:   pytestID(cassettePath),
		})
	}

	var buf bytes.Buffer
	buf.WriteString(`# Generated by agentreplay. Do not edit by hand.
from __future__ import annotations

import sys
from pathlib import Path

import pytest


def _prefer_local_agentreplay() -> None:
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "python" / "agentreplay" / "__init__.py"
        if candidate.exists():
            sys.path.insert(0, str(parent / "python"))
            return


_prefer_local_agentreplay()
from agentreplay.pytest import replay_case


_HERE = Path(__file__).resolve().parent

CASSETTES = [
`)
	for _, cassette := range cassettes {
		fmt.Fprintf(
			&buf,
			"    pytest.param(_HERE / %s, id=%s),\n",
			strconv.Quote(cassette.Path),
			strconv.Quote(cassette.ID),
		)
	}
	buf.WriteString(`]


@pytest.mark.parametrize("cassette", CASSETTES)
def test_agent_replay_regression(cassette: Path) -> None:
    result = replay_case(cassette)
    assert result.status == "passed"
    assert result.divergence_count == 0
`)

	return buf.Bytes(), nil
}

type generatedCassette struct {
	Path string
	ID   string
}

func validateGenerationCassette(path string) error {
	report, err := ValidateFile(path)
	if err != nil {
		return err
	}
	if !report.Valid() {
		return invalidCassetteError(report)
	}
	return nil
}

func relativeTestPath(cassettePath string, outputPath string) (string, error) {
	absCassette, err := filepath.Abs(cassettePath)
	if err != nil {
		return "", fmt.Errorf("resolve cassette path %q: %w", cassettePath, err)
	}
	absOutput, err := filepath.Abs(outputPath)
	if err != nil {
		return "", fmt.Errorf("resolve output path %q: %w", outputPath, err)
	}

	rel, err := filepath.Rel(filepath.Dir(absOutput), absCassette)
	if err != nil {
		return filepath.ToSlash(absCassette), nil
	}
	return filepath.ToSlash(rel), nil
}

func pytestID(path string) string {
	base := filepath.Base(path)
	id := strings.TrimSuffix(base, ".jsonl")
	id = strings.TrimSuffix(id, ".replay")
	if id == "" {
		return "cassette"
	}
	return id
}
